/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CoSoHinhThanhRouteImport } from './routes/co-so-hinh-thanh'
import { Route as ContributionRouteImport } from './routes/contribution'
import { Route as GiaTriTuTuongRouteImport } from './routes/gia-tri-tu-tuong'
import { Route as LuanBanRouteImport } from './routes/luan-ban'
import { Route as MRouteImport } from './routes/m'
import { Route as QuaTrinhPhatTrienRouteImport } from './routes/qua-trinh-phat-trien'
import { Route as QuanLyRouteImport } from './routes/quan-ly'
import { Route as TuLieuAnhRouteImport } from './routes/tu-lieu-anh'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoSoHinhThanhRoute = CoSoHinhThanhRouteImport.update({
  id: '/co-so-hinh-thanh',
  path: '/co-so-hinh-thanh',
  getParentRoute: () => rootRouteImport,
} as any)
const ContributionRoute = ContributionRouteImport.update({
  id: '/contribution',
  path: '/contribution',
  getParentRoute: () => rootRouteImport,
} as any)
const GiaTriTuTuongRoute = GiaTriTuTuongRouteImport.update({
  id: '/gia-tri-tu-tuong',
  path: '/gia-tri-tu-tuong',
  getParentRoute: () => rootRouteImport,
} as any)
const LuanBanRoute = LuanBanRouteImport.update({
  id: '/luan-ban',
  path: '/luan-ban',
  getParentRoute: () => rootRouteImport,
} as any)
const MRoute = MRouteImport.update({
  id: '/m',
  path: '/m',
  getParentRoute: () => rootRouteImport,
} as any)
const QuaTrinhPhatTrienRoute = QuaTrinhPhatTrienRouteImport.update({
  id: '/qua-trinh-phat-trien',
  path: '/qua-trinh-phat-trien',
  getParentRoute: () => rootRouteImport,
} as any)
const QuanLyRoute = QuanLyRouteImport.update({
  id: '/quan-ly',
  path: '/quan-ly',
  getParentRoute: () => rootRouteImport,
} as any)
const TuLieuAnhRoute = TuLieuAnhRouteImport.update({
  id: '/tu-lieu-anh',
  path: '/tu-lieu-anh',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/co-so-hinh-thanh': typeof CoSoHinhThanhRoute
  '/contribution': typeof ContributionRoute
  '/gia-tri-tu-tuong': typeof GiaTriTuTuongRoute
  '/luan-ban': typeof LuanBanRoute
  '/m': typeof MRoute
  '/qua-trinh-phat-trien': typeof QuaTrinhPhatTrienRoute
  '/quan-ly': typeof QuanLyRoute
  '/tu-lieu-anh': typeof TuLieuAnhRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/co-so-hinh-thanh': typeof CoSoHinhThanhRoute
  '/contribution': typeof ContributionRoute
  '/gia-tri-tu-tuong': typeof GiaTriTuTuongRoute
  '/luan-ban': typeof LuanBanRoute
  '/m': typeof MRoute
  '/qua-trinh-phat-trien': typeof QuaTrinhPhatTrienRoute
  '/quan-ly': typeof QuanLyRoute
  '/tu-lieu-anh': typeof TuLieuAnhRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/co-so-hinh-thanh': typeof CoSoHinhThanhRoute
  '/contribution': typeof ContributionRoute
  '/gia-tri-tu-tuong': typeof GiaTriTuTuongRoute
  '/luan-ban': typeof LuanBanRoute
  '/m': typeof MRoute
  '/qua-trinh-phat-trien': typeof QuaTrinhPhatTrienRoute
  '/quan-ly': typeof QuanLyRoute
  '/tu-lieu-anh': typeof TuLieuAnhRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/co-so-hinh-thanh'
    | '/contribution'
    | '/gia-tri-tu-tuong'
    | '/luan-ban'
    | '/m'
    | '/qua-trinh-phat-trien'
    | '/quan-ly'
    | '/tu-lieu-anh'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/co-so-hinh-thanh'
    | '/contribution'
    | '/gia-tri-tu-tuong'
    | '/luan-ban'
    | '/m'
    | '/qua-trinh-phat-trien'
    | '/quan-ly'
    | '/tu-lieu-anh'
  id:
    | '__root__'
    | '/'
    | '/co-so-hinh-thanh'
    | '/contribution'
    | '/gia-tri-tu-tuong'
    | '/luan-ban'
    | '/m'
    | '/qua-trinh-phat-trien'
    | '/quan-ly'
    | '/tu-lieu-anh'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CoSoHinhThanhRoute: typeof CoSoHinhThanhRoute
  ContributionRoute: typeof ContributionRoute
  GiaTriTuTuongRoute: typeof GiaTriTuTuongRoute
  LuanBanRoute: typeof LuanBanRoute
  MRoute: typeof MRoute
  QuaTrinhPhatTrienRoute: typeof QuaTrinhPhatTrienRoute
  QuanLyRoute: typeof QuanLyRoute
  TuLieuAnhRoute: typeof TuLieuAnhRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/co-so-hinh-thanh': {
      id: '/co-so-hinh-thanh'
      path: '/co-so-hinh-thanh'
      fullPath: '/co-so-hinh-thanh'
      preLoaderRoute: typeof CoSoHinhThanhRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contribution': {
      id: '/contribution'
      path: '/contribution'
      fullPath: '/contribution'
      preLoaderRoute: typeof ContributionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gia-tri-tu-tuong': {
      id: '/gia-tri-tu-tuong'
      path: '/gia-tri-tu-tuong'
      fullPath: '/gia-tri-tu-tuong'
      preLoaderRoute: typeof GiaTriTuTuongRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/luan-ban': {
      id: '/luan-ban'
      path: '/luan-ban'
      fullPath: '/luan-ban'
      preLoaderRoute: typeof LuanBanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/m': {
      id: '/m'
      path: '/m'
      fullPath: '/m'
      preLoaderRoute: typeof MRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qua-trinh-phat-trien': {
      id: '/qua-trinh-phat-trien'
      path: '/qua-trinh-phat-trien'
      fullPath: '/qua-trinh-phat-trien'
      preLoaderRoute: typeof QuaTrinhPhatTrienRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quan-ly': {
      id: '/quan-ly'
      path: '/quan-ly'
      fullPath: '/quan-ly'
      preLoaderRoute: typeof QuanLyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tu-lieu-anh': {
      id: '/tu-lieu-anh'
      path: '/tu-lieu-anh'
      fullPath: '/tu-lieu-anh'
      preLoaderRoute: typeof TuLieuAnhRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CoSoHinhThanhRoute: CoSoHinhThanhRoute,
  ContributionRoute: ContributionRoute,
  GiaTriTuTuongRoute: GiaTriTuTuongRoute,
  LuanBanRoute: LuanBanRoute,
  MRoute: MRoute,
  QuaTrinhPhatTrienRoute: QuaTrinhPhatTrienRoute,
  QuanLyRoute: QuanLyRoute,
  TuLieuAnhRoute: TuLieuAnhRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
